# Generated by Django 5.1 on 2024-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_doctorregistration_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(max_length=200)),
                ('slot_duration', models.TextField()),
            ],
        ),
    ]
