# Generated by Django 5.1 on 2024-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_doctor_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_slot', models.TextField()),
            ],
        ),
    ]
