# Generated by Django 5.1 on 2024-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booked_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
