# Generated by Django 5.1 on 2024-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_booked_appointment_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.PositiveIntegerField()),
                ('Doctor_id', models.PositiveIntegerField()),
                ('doctor_name', models.CharField(max_length=200)),
                ('booked_slot', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('purpose', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('is_virtual', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
