# Generated by Django 5.1 on 2024-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_virtual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
