# Generated by Django 5.1 on 2024-11-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_appointment_is_virtual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booked_appointment',
            new_name='booking_status',
        ),
    ]
